export type DataLayer = "staging" | "canonical" | "derived" | "intelligence" | "system";

export type TableRegistryEntry = {
  table: string;
  layer: DataLayer;
  purpose: string;
  keyColumns: string[];
  liveRoute: string;
  fedBy: string[];
  feeds: string[];
};

export const LAYER_LABELS: Record<DataLayer, string> = {
  staging: "Staging",
  canonical: "Canonical",
  derived: "Derived / search",
  intelligence: "Intelligence",
  system: "System",
};

export const RFQ_FLOW_STEPS = [
  {
    step: 1,
    label: "Upload evidence",
    table: "documents · procurement_packages",
    route: "/ingestion/intake",
    output: "Immutable file in Storage + document_versions.sha256 + package link",
  },
  {
    step: 2,
    label: "AI extract (staging only)",
    table: "extracted_facts",
    route: "/ingestion/processing",
    output: "AI_EXTRACTED facts — not trusted yet",
  },
  {
    step: 3,
    label: "Human verify",
    table: "extracted_facts",
    route: "/ingestion/verification",
    output: "HUMAN_VERIFIED → full promote chain (verified / contract / intelligence / chunk)",
  },
  {
    step: 4,
    label: "Canonical + intelligence promotion",
    table: "pricing_lines · requirements · awards · contracts · competitor_*",
    route: "/pursuits",
    output: "Four commercial truths + contracts/intel per document-table map",
  },
  {
    step: 5,
    label: "Searchable knowledge",
    table: "document_chunks",
    route: "/intelligence/ask",
    output: "Ask GPT cites verified chunks for the next RFQ",
  },
  {
    step: 6,
    label: "Outcome → contract / rebid",
    table: "win_loss_reviews · contracts · renewals",
    route: "/intelligence/win-loss",
    output: "Documented reasons + current contract truth for rebid",
  },
] as const;

export const TABLE_REGISTRY: TableRegistryEntry[] = [
  {
    table: "documents",
    layer: "staging",
    purpose: "Evidence registry — every uploaded file",
    keyColumns: ["original_filename", "document_type", "commercial_truth", "processing_status", "opportunity_id"],
    liveRoute: "/ingestion/intake",
    fedBy: ["Intake upload", "Bulk migration", "Pilot harness"],
    feeds: ["extracted_facts", "document_versions", "procurement_packages"],
  },
  {
    table: "document_versions",
    layer: "staging",
    purpose: "Immutable vault versions (SHA-256, storage path)",
    keyColumns: ["sha256", "storage_path", "is_current", "source_drive_file_id"],
    liveRoute: "/ingestion/intake",
    fedBy: ["register_ingested_document RPC"],
    feeds: ["extraction_runs", "signed PDF in verification workbench"],
  },
  {
    table: "extracted_facts",
    layer: "staging",
    purpose: "AI + human field values before promotion",
    keyColumns: ["field", "entity", "normalized_value", "verified_value", "verification_status", "source_page"],
    liveRoute: "/ingestion/verification",
    fedBy: ["Processor (store.py)"],
    feeds: ["pricing_lines", "requirements", "contracts", "competitor_*", "document_chunks"],
  },
  {
    table: "validation_exceptions",
    layer: "staging",
    purpose: "Promotion conflicts — rate/truth overwrite refused",
    keyColumns: ["code", "message", "document_id", "resolved"],
    liveRoute: "/ingestion/exceptions",
    fedBy: ["promote_verified_fact RPC on conflict"],
    feeds: ["Human resolution → re-verify source fact"],
  },
  {
    table: "staffing_requirements",
    layer: "canonical",
    purpose: "Post orders — armed/unarmed, shifts, weekly hours per pursuit",
    keyColumns: ["post_label", "armed", "posts_count", "weekly_hours", "source_fact_id"],
    liveRoute: "/pursuits",
    fedBy: ["Ops entry", "Future verified extraction"],
    feeds: ["Proposal staffing plan", "Cost modeling"],
  },
  {
    table: "evaluation_criteria",
    layer: "canonical",
    purpose: "RFP evaluation factors and optional weights",
    keyColumns: ["criterion", "weight_pct", "source_fact_id"],
    liveRoute: "/pursuits",
    fedBy: ["Ops entry", "Verified extraction from Section M"],
    feeds: ["Go/no-go", "Competitor brief"],
  },
  {
    table: "pricing_cost_models",
    layer: "intelligence",
    purpose: "Planning-only L&P cost stack and margin — not canonical proposed_rate",
    keyColumns: ["labor_category", "base_wage", "planned_proposed_rate", "target_margin_pct"],
    liveRoute: "/pursuits",
    fedBy: ["Ops coordinator saves in pricing workbench"],
    feeds: ["Margin analysis vs verified four-truth comparables"],
  },
  {
    table: "opportunities",
    layer: "canonical",
    purpose: "L&P package / pursuit hub",
    keyColumns: ["title", "client_id", "stage", "go_no_go", "procurement_rail", "solicitation_kind", "response_due_on", "service_type"],
    liveRoute: "/pursuits",
    fedBy: ["Intake form", "Identity promotion from verified facts"],
    feeds: ["pricing_lines", "solicitations", "awards", "documents.opportunity_id"],
  },
  {
    table: "clients",
    layer: "canonical",
    purpose: "Buyer / agency (not CRM)",
    keyColumns: ["name"],
    liveRoute: "/intelligence/clients",
    fedBy: ["Intake", "Identity promotion"],
    feeds: ["opportunities", "contracts", "research_facts filter"],
  },
  {
    table: "pricing_lines",
    layer: "canonical",
    purpose: "Four commercial truths — separate rate columns",
    keyColumns: [
      "labor_category",
      "requested_rate",
      "proposed_rate",
      "awarded_rate",
      "current_rate",
      "*_source_fact_id",
    ],
    liveRoute: "/intelligence/pricing",
    fedBy: ["promote_verified_fact from verified pricing facts"],
    feeds: ["Pursuit Pricing Glide", "Ask (via chunks)"],
  },
  {
    table: "requirements",
    layer: "canonical",
    purpose: "Canonical requirement statements from requested sources",
    keyColumns: ["statement", "solicitation_id", "source_fact_id"],
    liveRoute: "/pursuits",
    fedBy: ["promote_verified_fact (requested docs only)"],
    feeds: ["Pursuit Requirements matrix", "Response workspace"],
  },
  {
    table: "awards",
    layer: "canonical",
    purpose: "Award notice promoted from verified facts",
    keyColumns: ["notice", "awarded_on", "amount_nte", "winner_name", "source_fact_id"],
    liveRoute: "/pursuits",
    fedBy: ["promote_verified_fact"],
    feeds: ["Pursuit Result", "Contract promotion"],
  },
  {
    table: "contracts",
    layer: "canonical",
    purpose: "Current contract truth after award (workspace Overview)",
    keyColumns: ["title", "contract_number", "verified_end_on", "source_fact_id"],
    liveRoute: "/contracts",
    fedBy: ["promote_contract_from_fact"],
    feeds: ["contract_alerts", "renewals", "compliance_items", "contract_service_plans"],
  },
  {
    table: "contract_service_plans",
    layer: "canonical",
    purpose: "Verified sites/posts/classifications/hours on awarded contracts",
    keyColumns: ["site_name", "post_label", "guard_classification", "hours_per_week"],
    liveRoute: "/contracts",
    fedBy: ["promote_contract_from_fact"],
    feeds: ["Contract Service Plan tab"],
  },
  {
    table: "document_chunks",
    layer: "derived",
    purpose: "Verified text for FTS + vector search",
    keyColumns: ["content", "source_fact_id", "reuse_status", "is_current_version", "embedding"],
    liveRoute: "/intelligence/content",
    fedBy: ["promote_knowledge_chunk_from_fact + embedVerifiedChunk"],
    feeds: ["search_verified_knowledge → Ask GPT"],
  },
  {
    table: "win_loss_reviews",
    layer: "intelligence",
    purpose: "Documented evaluator reason vs internal analysis",
    keyColumns: ["outcome", "documented_reason", "internal_analysis", "lp_price", "winning_price"],
    liveRoute: "/intelligence/win-loss",
    fedBy: ["promote_intelligence_from_fact"],
    feeds: ["Market counts", "Reports", "Rebid context"],
  },
  {
    table: "competitor_bids",
    layer: "intelligence",
    purpose: "Sourced competitor outcome / bid summary (not hourly grain)",
    keyColumns: ["quoted_amount", "rank", "note", "source_fact_id", "competitor_id"],
    liveRoute: "/intelligence/competitors",
    fedBy: ["promote_intelligence_from_fact"],
    feeds: ["Market overview", "Win/Loss"],
  },
  {
    table: "competitor_pricing_lines",
    layer: "intelligence",
    purpose: "Multi-vendor hourly/site rates from bid tabs — never L&P four-truth lines",
    keyColumns: ["vendor_name", "hourly_rate", "rate_type", "site_or_post", "source_fact_id"],
    liveRoute: "/intelligence/competitors",
    fedBy: ["promote_intelligence_from_fact (competitor_price)"],
    feeds: ["Pricing comps", "Pursuit Glide comparables"],
  },
  {
    table: "procurement_packages",
    layer: "canonical",
    purpose: "Buyer + opportunity document set (PKG-*); corpus_class A/B/C",
    keyColumns: ["package_key", "title", "corpus_class", "client_id", "opportunity_id"],
    liveRoute: "/ingestion/intake",
    fedBy: ["Pilot / intake package ensure"],
    feeds: ["documents.procurement_package_id"],
  },
  {
    table: "solicitations",
    layer: "canonical",
    purpose: "One solicitation per opportunity when requested facts promote",
    keyColumns: ["title", "solicitation_number", "opportunity_id"],
    liveRoute: "/pursuits",
    fedBy: ["promote_verified_fact"],
    feeds: ["requirements", "documents.solicitation_id"],
  },
  {
    table: "solicitation_addenda",
    layer: "canonical",
    purpose: "Addendum chain — precedence over base solicitation",
    keyColumns: ["addendum_number", "title", "source_document_id"],
    liveRoute: "/pursuits",
    fedBy: ["Verified addendum facts (schema ready)"],
    feeds: ["Requested truth precedence"],
  },
  {
    table: "required_forms",
    layer: "canonical",
    purpose: "Mandatory forms from IFB/RFP (HUB, references, cost sheet)",
    keyColumns: ["form_name", "mandatory", "source_document_id", "source_fact_id"],
    liveRoute: "/pursuits",
    fedBy: ["promote_required_form_from_fact"],
    feeds: ["Pursuit Requirements / Submission checklist"],
  },
  {
    table: "evaluation_scores",
    layer: "canonical",
    purpose: "Evaluator scorecard rows (L&P vs competitor)",
    keyColumns: ["vendor_name", "score", "criterion", "source_fact_id"],
    liveRoute: "/intelligence/win-loss",
    fedBy: ["promote when evaluation_score facts exist"],
    feeds: ["Win/Loss", "Competitor brief"],
  },
  {
    table: "proposal_sections",
    layer: "canonical",
    purpose: "Bound proposal section grain with source page",
    keyColumns: ["section_label", "content", "source_page", "source_fact_id"],
    liveRoute: "/intelligence/content",
    fedBy: ["Verified proposal_section facts"],
    feeds: ["Content reuse", "Response drafting"],
  },
  {
    table: "experience_records",
    layer: "canonical",
    purpose: "Typed past performance / experience — types never merge",
    keyColumns: [
      "experience_type",
      "attribution_language",
      "verification_status",
      "contract_id",
      "person_name",
      "employer_name",
      "subcontractor_name",
    ],
    liveRoute: "/intelligence/content",
    fedBy: ["promote_experience_from_contract", "typed extraction + verify.promote"],
    feeds: ["Response past-performance drafting", "Ask search_experience_records"],
  },
  {
    table: "experience_references",
    layer: "canonical",
    purpose: "Reference contacts for an experience_record (alone ≠ corporate PP)",
    keyColumns: ["experience_record_id", "contact_name", "agency_or_company"],
    liveRoute: "/intelligence/content",
    fedBy: ["Human / extract under experience_record"],
    feeds: ["Reference letters — never upgrades type to L_AND_P_CORPORATE"],
  },
  {
    table: "purchase_orders",
    layer: "canonical",
    purpose: "Awarded PO header linked to contract / opportunity",
    keyColumns: ["po_number", "payment_terms", "source_fact_id"],
    liveRoute: "/contracts",
    fedBy: ["promote_contract_from_fact"],
    feeds: ["purchase_order_lines", "Commercial Terms"],
  },
  {
    table: "purchase_order_lines",
    layer: "canonical",
    purpose: "PO line qty × rate / extended",
    keyColumns: ["description", "quantity", "unit_rate", "extended_amount"],
    liveRoute: "/contracts",
    fedBy: ["promote_contract_from_fact"],
    feeds: ["Commercial Terms"],
  },
  {
    table: "federal_identifiers",
    layer: "canonical",
    purpose: "TXMAS / GSA / vehicle IDs on instruments",
    keyColumns: ["scheme", "identifier", "source_fact_id"],
    liveRoute: "/contracts",
    fedBy: ["promote_contract_from_fact"],
    feeds: ["Contract Overview"],
  },
  {
    table: "contract_amendments",
    layer: "canonical",
    purpose: "Append-only amendment history",
    keyColumns: ["amendment_number", "title", "note", "source_fact_id"],
    liveRoute: "/contracts",
    fedBy: ["promote_contract_from_fact"],
    feeds: ["Changes tab"],
  },
  {
    table: "renewals",
    layer: "canonical",
    purpose: "Renewal / CPI / notice on contracts",
    keyColumns: ["notice", "escalation_index", "escalation_pct", "option_year"],
    liveRoute: "/contracts",
    fedBy: ["promote_contract_from_fact"],
    feeds: ["Renewal tab", "alert buckets"],
  },
  {
    table: "cost_build_components",
    layer: "intelligence",
    purpose: "Competitor/public cost stack (wage/FICA/WC/OH/profit)",
    keyColumns: ["component", "amount", "source_fact_id"],
    liveRoute: "/intelligence/pricing",
    fedBy: ["promote_cost_component_from_fact"],
    feeds: ["Pricing comps"],
  },
  {
    table: "research_runs",
    layer: "intelligence",
    purpose: "Bounded public research acquisition runs (F4)",
    keyColumns: ["research_type", "status", "query", "plan"],
    liveRoute: "/intelligence/research",
    fedBy: ["executeResearchRun"],
    feeds: ["research_sources", "research_facts"],
  },
  {
    table: "research_sources",
    layer: "intelligence",
    purpose: "Captured public URLs for a research run",
    keyColumns: ["url", "provider", "research_run_id"],
    liveRoute: "/intelligence/research",
    fedBy: ["recordSources"],
    feeds: ["research_facts"],
  },
  {
    table: "research_facts",
    layer: "intelligence",
    purpose: "Public-source buyer/competitor research (AI_EXTRACTED until human verifies)",
    keyColumns: ["source_url", "claim", "excerpt", "verification_status", "research_run_id"],
    liveRoute: "/intelligence/research",
    fedBy: ["F4 research pipeline", "Manual / promoted research"],
    feeds: ["Buyer intelligence briefs", "Ask verified research rail"],
  },
];

export function tablesForLayer(layer: DataLayer) {
  return TABLE_REGISTRY.filter((entry) => entry.layer === layer);
}

export function registryEntry(table: string) {
  return TABLE_REGISTRY.find((entry) => entry.table === table);
}
